### ISSUE TITLE
How can I build in android studio?

### ISSUE THREAD

**Issue by ekfriis** [krcla/KnowYourRightsApp#1]
Hi Zu, 

I downloaded Android Studio and tried to connect it to github. It downloaded, and asked if i wanted to setup gradle. I said yes, and it gave me this error:

Any ideas on what to do?

![android-studio-error](https://cloud.githubusercontent.com/assets/98621/24937950/0d767f70-1ee9-11e7-8d59-c84f5df7c8a9.png)

**Comment by zuwhan** [comment]
I added those two files. Hope it works.
